# Generated by Django 5.2.7 on 2025-11-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0003_waitlistentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
